Setting up the continuous integration pipeline and basic structure
ISISMuon/MuonDataLib pull request #1
Opened 2023-10-20 09:25 UTC by AnthonyLim23

This PR adds all of the setup needed for the repo. 

I have added a dummy function so we have some unit tests (add.py). This can be removed when we add a real bit of code.

I have added a conda file to help developers get easily setup. It also makes the unit testing easier as it sets up that environment too. It will also install pre-commit, which will run flake8 at the commit stage, allowing developers to correct their code without using a build server. 

I have added some rules for producing automatic release notes. The release notes will be generated from the PR titles. 

I have added the setup need for a PR template and docs (hosted on read the docs), see https://readthedocs.org/projects/muondatalib/builds/

For the default CI: 
 - flake8 
 - unit tests on ubuntu, windows and mac for Python 3.8 to 3.11
 - checks for merge conflicts

Once a PR is approved it will run the merge workflow. This will update the version in the setup.py, build the package, test the package and upload it to PyPi (every upload needs a unique version). It will then update this PR with the new version number. It can then be merged. 

When we want to do a proper release (major or minor), we will use the release-next branch. Merge in the main and set if its a minor or major bump in the release_next workflow. When we push the changes this will trigger the workflow. It will automatically update the version in setup.py (major or minor as selected), build and test the package (same as merge) and then commit the update to a new branch that we can use to create a PR and merge into main.

2023-10-20 15:58 UTC, AnthonyLim23 commented
To do:
- write something useful in docs
- setup automatic release pipelines

2023-10-23 09:45 UTC, AnthonyLim23 commented
https://github.com/marketplace/actions/add-commit

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

2023-10-25 16:42 UTC, AnthonyLim23 commented on docs/source/dev/setup.rst
> +Once it is completed you will need to use the command :code:`conda activate MuonDataLib` to get access to the environment.
```suggestion
Once it is completed you will need to use the command :code:`conda activate MuonDataLib-dev` to get access to the environment.
```

2023-10-25 16:44 UTC, AnthonyLim23 commented on docs/source/dev/index.rst
> +.. quickBayes documentation master file, created by
```suggestion
.. documentation master file, created by
```

2023-10-25 16:44 UTC, AnthonyLim23 commented on docs/source/index.rst
> +.. quickBayes documentation master file, created by
```suggestion
.. documentation master file, created by
```

2023-10-26 10:26 UTC, franzlang commented on .github/workflows/merge.yml
> +    types: [submitted]
If I understand this correctly this workflow runs whenever a PR review was submitted. Not when a PR was successfully merged. Therefore, would this workflow be triggered even if a PR review had the outcome `request changes`?

2023-10-26 10:45 UTC, AnthonyLim23 commented on .github/workflows/merge.yml
> +    types: [submitted]
I missed the if statement that checks that the PR has been approved, I have added it now. Since all of the subsequent checks require the first one to pass, they will not run if the PR is not approved.

2023-10-26 13:05 UTC, wilkojohnny commented on .github/release.yml
> +        - bug
I don't think it really matters either way -- what's usual practice?

2023-10-26 14:13 UTC, AnthonyLim23 commented on .github/release.yml
> +        - bug
looks like minuit does features then bugs https://github.com/jpivarski/pyminuit2/blob/master/RELEASE_NOTES

I dont think there is an accepted order. Everyone seems to do something different (scipy just list the closed issues and PRs).

2023-10-26 14:28 UTC, wilkojohnny commented on .github/release.yml
> +        - bug
Thanks -- in that case, perhaps we should just leave it as it is.

2023-10-26 15:45 UTC, franzlang requested changes
looks good to me. found some minor typos and had a few questions that might be me being slow.

2023-10-26 15:45 UTC, franzlang commented on docs/source/dev/setup.rst
> +To reduce the chances of problems Conda (alternatively you can use mamba) to manage the setup of the development environment (this is also used for the continuous integration).
missing word?

2023-10-26 15:45 UTC, franzlang commented on docs/source/dev/setup.rst
> +The exit your conda environment with :code:`conda deactivate`.
grammar?

2023-10-26 15:45 UTC, franzlang commented on docs/source/dev/setup.rst
> +To build your local version use :code:`python -m pip install -v --editable .`, the full stop is important.
`-e` is also possible instead of `--editable` I believe

2023-10-26 15:45 UTC, franzlang commented on docs/source/index.rst
> +Welcome to quickBayes's documentation!
this should be changed to WiMDA?

2023-10-26 15:45 UTC, franzlang commented on src/MuonDataLib/makefile.txt
is this empty by design for now?

2023-10-27 07:44 UTC, AnthonyLim23 commented on MuonDataLib.yml
> +  - python =3.10.*
```suggestion
  - python =3.11.*
```

2023-10-27 07:45 UTC, AnthonyLim23 commented on docs/source/dev/setup.rst
> +To reduce the chances of problems Conda (alternatively you can use mamba) to manage the setup of the development environment (this is also used for the continuous integration).
```suggestion
To reduce the chances of problems; Conda (alternatively you can use mamba) is used to manage the setup of the development environment (it is also used for the continuous integration).
```

2023-10-27 07:46 UTC, AnthonyLim23 commented on docs/source/dev/setup.rst
> +The exit your conda environment with :code:`conda deactivate`.
```suggestion
To exit your conda environment type :code:`conda deactivate` into the terminal.
```

2023-10-27 07:47 UTC, AnthonyLim23 commented on docs/source/index.rst
> +Welcome to quickBayes's documentation!
thought I caught all of these. 

```suggestion
Welcome to MuonDataLib's documentation!
```

2023-10-27 07:48 UTC, AnthonyLim23 commented on src/MuonDataLib/makefile.txt
yes, these work like makefiles in C++. The build script searches the src directory recursively to find all of the makefiles and they then define how to relate each python file with a module.

2023-10-27 07:49 UTC, AnthonyLim23 commented on docs/source/dev/setup.rst
> +To build your local version use :code:`python -m pip install -v --editable .`, the full stop is important.
```suggestion
To build your local version use :code:`python -m pip install -v -e .`, the full stop is important.
```

2023-10-27 10:22 UTC, AnthonyLim23 commented on .github/PULL_REQUEST_TEMPLATE.md
> + - New Feature
```suggestion
 - New Feature
 - bug
```

2023-10-27 10:23 UTC, franzlang submitted a review, later dismissed
looks good to me now. can be merged once the tests have all passed

2023-10-27 11:18 UTC, AnthonyLim23 commented
The latest 2 commits adds some scripts for creating yml files. This allows the experienced developer (and the build servers) to explicitly specify the Python version for the conda recipe. This will make it easier to build and check against specific Python versions.

The merge and release workflows didnt need changing as they do not use conda.

2023-10-27 12:41 UTC, franzlang submitted a review, later dismissed
found 3 minor typos in documentation/dev comments. functionally this looks fine to me.

2023-10-27 12:41 UTC, franzlang commented on tools/conda_dict_to_yml.py
> +Written a custom passer to write yml file
parser?

2023-10-27 12:41 UTC, franzlang commented on tools/conda_dict_to_yml.py
> +    Adds the packagesto be installed by pip to the file
`packages to`

2023-10-27 12:41 UTC, franzlang commented on tools/create_conda_yml.py
> +Here we list the conda recipies.
recipes

2023-10-27 13:39 UTC, AnthonyLim23 commented on tools/conda_dict_to_yml.py
> +Written a custom passer to write yml file
```suggestion
Written a custom parser to write yml file
```

2023-10-27 13:39 UTC, AnthonyLim23 commented on tools/conda_dict_to_yml.py
> +    Adds the packagesto be installed by pip to the file
```suggestion
    Adds the packages to be installed by pip to the file
```

2023-10-27 13:39 UTC, AnthonyLim23 commented on tools/create_conda_yml.py
> +Here we list the conda recipies.
```suggestion
Here we list the conda recipes.
```

2023-11-01 09:06 UTC, franzlang submitted a review, later dismissed
looks good to me.

2023-11-07 15:47 UTC, franzlang approved these changes

2023-11-07 16:20 UTC, merged